language: node_js

os: linux

dist: focal

node_js:
  - lts/*

install:
  - yarn

script:
  - NODE_OPTIONS='--max-old-space-size=4096' yarn build:all
  - yarn turbo run check-types
  - xvfb-run --server-args="-screen 0 1920x1080x24" yarn test
