name: Tests

on: [push, pull_request_target]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js lts/*
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: yarn

      - name: Build Project
        run: yarn build:all

      - name: Check types
        run: yarn turbo run check-types

      - name: Run tests
        run: xvfb-run --server-args="-screen 0 1920x1080x24" yarn test
